# Generated by Django 4.1.7 on 2023-03-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_sub_category_product_subcategory_orders_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
